### ISSUE TITLE
Move to @ember-intl scope on npm

### ISSUE THREAD

**Issue by buschtoens** [ember-intl/decorators#2]
@jasonmit Can you add me to the [`@ember-intl/*` org](https://www.npmjs.com/org/ember-intl) on npm, so that I can republish this packages as `@ember-intl/decorators`? Or would you rather keep this separate?

**Comment by jasonmit** [comment]
@buschtoens done!

**Comment by buschtoens** [comment]
Awesome, thank you!

I've published [`@ember-intl/decorators`](https://www.npmjs.com/package/@ember-intl/decorators) and [deprecated the old package.](https://www.npmjs.com/package/ember-intl-decorators)
